src/entity/tour/LastMinuteOffer.java
package entity.tour;

public class LastMinuteOffer extends Decorator {
    private double sale = 10;

    public LastMinuteOffer(Order order) {
        super(order);
    }

    public LastMinuteOffer(Order order, double sale) {
        super(order);
        this.sale = sale;
    }

    public double getOffer() {
        return sale;
    }

    @Override
    public double getPrice() {
        return order.getPrice() * ((100 - sale) / 100);
    }
}

src/controller/servlets/HomeServlet.java
/*
 * Стартовый сервлет. Welcome-file не сделал. 
 * Welcome-jsp я так понял был бы страницей со статическим наполнением, а я решил сразу отображать данные
 * из таблицы tours_list, поэтому запускал этот сервлет первым, чтобы попасть на стартовую страницу 
 * с динамическими данными.
 * С сервлетами ранее знаком не был, поэтому в этом пакете они все выполнены по принципу "работает - и хорошо",
 * чтобы была хоть какая-то функциональность.
 */

package controller.servlets;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import entity.Tour;
import exceptions.ServiceException;
import service.FactoryException;
import service.ServiceFactory;
import service.TourService;
import service.logic.MainServiceFactoryImpl;

@WebServlet("/HomeServlet")
public class HomeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        List<Tour> tours = new ArrayList<Tour>();
        try {
            ServiceFactory fact = new MainServiceFactoryImpl();
            TourService service = fact.getTourService();
            tours = service.readAllTour();
        } catch (FactoryException | ServiceException e) {
            throw new ServletException(e);
        }
        request.setAttribute("t", tours);
        RequestDispatcher disp = getServletContext().getRequestDispatcher("/home.jsp");
        disp.forward(request, response);
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        doGet(request, response);
    }
}

WebContent/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<footer
		class="container">
	<div class="row">
		<p class="col-sm-4">&copy; 2018 Автор</p>
		<ul class="col-sm-8">
			<li class="col-sm-1"><img
				src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/twitter.svg"></li>
			<li class="col-sm-1"><img
				src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/facebook.svg"></li>
			<li class="col-sm-1"><img
				src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/instagram.svg"></li>
			<li class="col-sm-1"><img
				= src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/medium.svg"></li>
		</ul>
	</div>
	</footer>
</body>
</html>

WebContent/home.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ page errorPage="error.jsp"%>
<%@ include file="login.jsp"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Start page</title>
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
	integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
	crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700'
	rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="main.css">
</head>
<body>
<h5> Кнопки edit and delete ничего не делают</h5>
	<header class="container">
	<div class="row">
		<h1 class="col-sm-8">Турфирма</h1>
		<nav class="col-sm-12">
		<p>
		<form action="ClientList" method="get">
			<input type="submit" name="clients" value="Clients" />
		</form>
		</p>
		<p>
		<form action="SaleList" method="get">
			<input type="submit" name="sales" value="Sales" />
		</form>
		</p>
		<p>
		<form action="Contacts" method="get">
			<input type="submit" name="contacts" value="Contscts" />
		</form>
		</p>
		</nav>
	</div>
	<table border="1">
		<caption>Список туров</caption>
		<tr>
			<th>Город</th>
			<th>Тип поездки</th>
			<th>Цена</th>
			<th>Дни</th>
			<th>Еда</th>
			<th>Отель</th>
			<th>Виза</th>
			<th>Транспорт</th>
		</tr>
		<c:forEach var="tour" items="${t}">
			<tr>
				<td>${tour.city}</td>
				<td>${tour.type}</td>
				<td>${tour.price}</td>
				<td>${tour.days}</td>
				<td>${tour.eat}</td>
				<td>${tour.hotel}</td>
				<td>${tour.visa}</td>
				<td>${tour.transBus}</td>
				<td><input type="submit" name="enter" value="Edit" /></td>
				<td><input type="submit" name="enter" value="Delete" /></td>
			</tr>
		</c:forEach>
	</table>
	<form action="CreateTour" method="get">
		<input type="submit" name="createTour" value="Create new tour" />
	</form>
	<%@ include file="footer.jsp"%>
</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>	

	<form action="Test01" method="post" >
		Login: <input type="text" name="login" />
		Password: <input type="password" name="password" />
		<input type="submit" name="enter" value="Login in" />
		<input type="submit" name="register" value="Registration" />
	</form>

</body>
</html>